spring:
  application:
    name: bangflex-monolithic

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://217.142.246.78:3306/bangflex
    username: 'root'
    password: 'bangpw'

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ## redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    springbootmonolithic: DEBUG
    org:
      springframework:
        security:
          web:
            FilterChainProxy: TRACE

file:
  path: src/main/resources/static/

token:
  access:
    expiration_time: 400000
  refresh:
    expiration_time: 1500000
  secret: Wa2Xodz8URmigeXhI+moDopYsQiMzMI2BMz4j88kYCTdO+xiFjkinsjiTRlX0+Z7bUL0E+A9Fq6IpzlUBotvaw==

## SMTP
mail:
  host: smtp.gmail.com
  port: 587
  username: "bangflixvarc@gmail.com"
  password: "omxt efoi angl icgw"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  expiration_time: 180000 # 3? (1000 * 60 * 3)

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    defaults:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
