groups:
  - name: example-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status="500"}[5m]) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected on {{ $labels.instance }}"
          description: "Error rate is above 5% for the last 5 minutes."
