global:
  scrape_interval: 5s  # 메트릭 수집 간격

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springboot-app:8080']  # Spring Boot 애플리케이션

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # 시스템 메트릭 수집
